name: taxlien.online
description: "Mobile application for investing in tax liens"
publish_to: 'none'

version: 2.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  
  # Core dependencies
  http: ^1.1.0
  shared_preferences: ^2.2.0
  sqflite: ^2.3.0
  path: ^1.8.3
  url_launcher: ^6.2.1
  webview_flutter: ^4.4.2
  
  # UI/UX improvements
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  shimmer: ^3.0.0
  lottie: ^3.3.1
  
  # State management
  provider: ^6.1.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  
  # Navigation
  go_router: ^16.2.0
  
  # Forms and validation
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.1.0
  
  # Charts and data visualization
  fl_chart: ^1.0.0
  
  # Animations
  flutter_animate: ^4.2.0+1
  
  # Localization
  intl: ^0.20.2
  
  # Security
  crypto: ^3.0.3
  flutter_secure_storage: ^9.0.0
  
  # Networking
  dio: ^5.3.2
  connectivity_plus: ^6.1.5
  
  # Image handling
  image_picker: ^1.0.4
  image_cropper: ^9.1.0
  
  # QR Code
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  
  # Notifications
  flutter_local_notifications: ^19.4.0
  
  # Biometrics
  local_auth: ^2.1.6
  
  # File handling
  file_picker: ^10.3.2
  permission_handler: ^12.0.1
  
  # Social sharing
  share_plus: ^11.1.0
  
  # Deep linking
  uni_links: ^0.5.1
  
  # Analytics
  firebase_analytics: ^12.0.0
  firebase_crashlytics: ^5.0.0
  
  # Push notifications
  firebase_messaging: ^16.0.0
  
  # In-app purchases
  in_app_purchase: ^3.1.13
  
  # AdMob
  google_mobile_ads: ^6.0.0
  
  # Production optimizations
  dio_certificate_pinning: ^3.0.3
  network_info_plus: ^4.1.0
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0
  sentry_flutter: ^7.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  freezed_annotation: ^2.4.1
  mockito: ^5.4.2
  integration_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
